server {
    listen 443 ssl;
    server_name web2;

    ssl_certificate     /etc/nginx/certs/server2.crt;
    ssl_certificate_key /etc/nginx/certs/server2.key;

    ssl_client_certificate /etc/nginx/certs/ca.crt;
    ssl_verify_client on;

    location / {
        root  /usr/share/nginx/html;
        index index.html;
        add_header X-Client-Verify $ssl_client_verify;
        add_header X-Client-DN     $ssl_client_s_dn;
    }
}
