services:
  web1:
    image: nginx:stable
    container_name: web1
#    ports:
#      - "8443:443"
    volumes:
      - ./backends/web1/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backends/web1/html:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - mtls-net

  web2:
    image: nginx:stable
    container_name: web2
#    ports:
#      - "8444:443"
    volumes:
      - ./backends/web2/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backends/web2/html:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - mtls-net

networks:
  mtls-net:
    external: true
